### ISSUE TITLE
Two part deployment - Deploying part two from parameters file with privateacr set to true not working

### ISSUE THREAD

**Issue by jeevanions** [Azure/ipam#102] opened 2023-03-30 15:12 UTC
### Issue:

Due to our limited permission in Azure AD, we chose to do the two-part deployment. As part of stage 1, a parameters file is populated with the necessary parameters to deploy the infrastructure. 
In the parameter file, we changed the `privateAcr` flag to `true` and ran the deployment script. But it did not deploy a private ACR instance; instead used the default one.

### Steps:

1. Run deployment script in AppsOnly mode
```
./deploy.ps1 `
  -AppsOnly `
  -UIAppName "ui-app-reg" `
  -EngineAppName "engine-app-reg" 
```

2. Update the `privateAcr` flag to `true` in the auto generated `main.parameters.json` file 

3. Run the stage 2 deployment 

```
./deploy.ps1 `
  -Location "uksouth" `
  -ParameterFile ./main.parameters.json
```
### Expected:
Pushes images to private ACR.

**Comment by DCMattyG** [comment] 2023-03-30 16:47
Hey @jeevanions, in the documentation for the second stage of the 2-part deployment, it specifically calls out to set the ``-PrivateACR`` flag, not manipulate the ```main.parameters.json`` file. You can find the docs [here](https://azure.github.io/ipam/#/deployment/README?id=infrastructure-stack-only-deployment) for reference.

Did you try that perhaps? The parameters file was not intended to be manipulated manually.

**Comment by jeevanions** [comment] 2023-03-30 17:20
Thank you. I may have gotten so sophisticated. I am going to deploy again with this flag. I guess it will be a brand-new environment.

**Comment by DCMattyG** [comment] 2023-04-12 15:54
Good morning @jeevanions, I wanted to check-in with you on this issue. Were you able to get the 2-part deployment working, or can we be of any assistance to you here with troubleshooting?

**Comment by jeevhub** [comment] 2023-04-13 11:54
@DCMattyG  Yes it did work. We have concluded our POC and confirmed that we have all the functionality we needed. Just a final question regarding carving the IP blocks from the IP blocks; When we carve it we use different sizes and there might be possibilities we end up in unusable IP blocks  (this is myg guess and i don't have any proof to support this). Is there a chance we can restrict certain IP Blocks can only dispense pre configured IP prefixes like `/20`, `24`, etc. Like IP Block -> Allocate only subnet blocks of size `/18`.

**Comment by jeevhub** [comment] 2023-04-13 11:56
We are soon going to get this in the prod environment but would be nice if have the infra deployed through Terraform. I thought of doing it but you mentioned that someone is already working on this. Is there any movement on this?

**Comment by DCMattyG** [comment] 2023-04-13 16:25
@jeevhub, at the moment, but that is a wonderful idea!

We will be adding in some additional Admin settings in the near future, and I will add this suggestion to the roadmap.

**"Restrict CIDR block sizes for Reservation requests"**

I'm not sure if we'll be able to make it *"per block"* for the initial implementation, so would it be alright if it were **global** to start, then we explored the possibility of bringing it to the Block level?

**Comment by DCMattyG** [comment] 2023-09-19 02:56
Closing this issue because the original problem has been resolved, and the noted follow-up item in the above comment has been added to the official roadmap.

**Closed by DCMattyG** 2023-09-19 02:56 UTC
Labels: help wanted
