### ISSUE TITLE
Deploy.ps1 fails during UI Build due to UnicodeEncodeError

### ISSUE THREAD

**Issue by daveinci** [Azure/ipam#176] opened 2023-09-27 14:13 UTC
**Describe the bug**
Running deploy.ps1 fails during UI build phase, specifically during vite install, due to handling of error received during vite installation when it returns a checkmark (character '\u2713') in its result. Running the commands manually work. 

**To Reproduce**
1. Follow deployment instructions for "Full" deployment with PrivateACR and custom $ResourceNames defined. https://azure.github.io/ipam/#/deployment/README
2. See error: 
RUN npm run build  ---> Running in
     | cf61f8120ed6  > azure-ipam-ui@2.0.0 build > vite build  vite v4.4.9 building for production... transforming...  
     | ERROR: The command failed with an unexpected error. Here is the traceback: ERROR: 'charmap' codec can't encode
     | character '\u2713' in position 0: character maps to <undefined> Traceback (most recent call last):   File
     | "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\knack/cli.py", line 233, in invoke   File
     | "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line
     | 663, in execute   File
     | "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line
     | 726, in _run_jobs_serially   File
     | "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line
     | 697, in _run_job   File
     | "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line
     | 333, in __call__   File
     | "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/command_operation.py", line 121, in handler   File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/command_modules/acr/build.py", line 143, in acr_build   File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/command_modules/acr/_stream_utils.py", line 58, in stream_logs   File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/command_modules/acr/_stream_utils.py", line 143, in _stream_logs   File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\colorama/ansitowin32.py", line 41, in write   File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\colorama/ansitowin32.py", line 162, in write   File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\colorama/ansitowin32.py", line 187, in write_and_convert   File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\colorama/ansitowin32.py", line 195, in write_plain_text   File "encodings\cp1252.py", line 19, in encode UnicodeEncodeError: 'charmap' codec can't encode character '\u2713' in position 0: character maps to <undefined> To check existing issues, please visit: https://github.com/Azure/azure-cli/issues

**Expected behavior**
Expect deploy.ps1 to complete without error and ipam applications to be running in app service.
![Screenshot 2023-09-27 090219](https://github.com/Azure/ipam/assets/27959962/8fdfcafa-fc2c-426e-9cad-827a9b2a6617)

**Screenshots**
![image](https://github.com/Azure/ipam/assets/27959962/cedd8799-dc3c-4285-b8ef-f413aff12b65)

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] Windows 11, latest versions of prerequisites installed: PowerShell 7.3.7, Bicep 0.21.1, Az CLI 2.53.0, python 3.11.5
 - Browser [e.g. chrome, safari] N/A

**Smartphone (please complete the following information):**

**Additional context**

**Comment by DCMattyG** [comment] 2023-09-27 15:37
Good morning @daveinci, I'm working on reproducing this now and will circle back with you shortly once I have some answers on the best way to address this. Thank you so much for bringing this to my attention!

**Comment by DCMattyG** [comment] 2023-09-28 05:13
Hey @daveinci, the root cause for this stems from how the Vite build process will emit an Unicode "checkmark" character, and then that being captured by PowerShell and redirected to a variable. Long story short, this is an issue with how this is handled in Windows systems, but there is something you can try as a workaround for now.

Take a look at the fix in this link, which shows how to enable UTF-8 support in Windows:
https://github.com/microsoft/knack/pull/178

I would suggest enabling that **for now** and seeing if that unblocks you, and in the meantime I will continue working on a more permanent/universal fix for this issue.

Please let me know if the above helps!

**Comment by daveinci** [comment] 2023-09-28 13:56
Thanks @DCMattyG. I worked around by running the 'az acr build' commands manually. Enabling Control Panel -> Region -> Administrative -> Change system locale -> Beta: Use Unicode UTF-8 for worldwide language support would likely do the trick but appreciate you looking for the permanent/universal fix. Think that will help users.

**Comment by DCMattyG** [comment] 2023-10-08 04:05
Hi @daveinci, this issue has been addressed in PR #181. For now, I've changed the output of the build to "warn" which will stop the Unicode output seen at the "info" level. I've tested four many hours trying to find a way to alleviate this via scripting, but it appears unless you enable UTF-8 support in Windows (as mentioned in my previous comment), nothing I've found through script changes has been able to alleviate this issue.

I'll keep looking for a better workaround, but now this issue should be resolved. Please let me know if you have any further issues and we'll get right on them. Thanks again!

**Closed by DCMattyG** 2023-10-08 04:05 UTC
Labels: bug
