### ISSUE TITLE
Deployment script produces poor logs when failing on Function only deployment 

### ISSUE THREAD

**Issue by craigthackerx** [Azure/ipam#109] opened 2023-04-05 11:30 UTC
**Describe the bug**
When trying to deploy using the function only deployment, poor error messages are given with little information.  Setting debug trace in PowerShell *slightly* helps.

**To Reproduce**
Run deploy script as follows 
```
PS /home/craig/craig-workspace/azure-ipam/deploy> ./deploy.ps1 `
>>   -Location "uksouth" `
>>   -AsFunction
NOTE: IPAM Deployment Type: Function
INFO: Fetching Tenant ID from Azure PowerShell SDK
INFO: Fetching Azure Cloud type from Azure PowerShell SDK
INFO: Validating Azure Region selected for deployment
INFO: Azure Region validated successfully
INFO: Creating Azure IPAM Engine Application
INFO: Creating Azure IPAM Engine Service Principal
INFO: Creating Azure IPAM Engine Secret
INFO: Azure IPAM Engine & UI Applications/Service Principals created successfully
INFO: Logging in to Microsoft Graph
INFO: Granting admin consent for Azure Service Management API permissions assigned to IPAM Engine application
INFO: Admin consent for Azure Service Management API permissions granted successfully
INFO: Deploying IPAM bicep templates
ERROR: Unable to deploy Azure IPAM solution due to an exception, see logs for detailed information!
Run Log: ../logs/deploy_20230405121940PM.log
Error Log: ../logs/error_20230405121940PM.log
```
I have Global Admin and owner on my context subscription. I am connected using PowerShell and Azure-Cli on the same context.

**Expected behavior**
Logs saying what's wrong are more descriptive.

**Deploy log**
```
********************** PowerShell transcript start Start time: 20230405121940 Username: blah RunAs User: blah Configuration Name: Machine: blah (Unix 5.15.90.1) Host Application: /opt/microsoft/powershell/7/pwsh.dll Process ID: 4753 PSVersion: 7.3.3 PSEdition: Core GitCommitId: 7.3.3 OS: Linux 5.15.90.1-microsoft-standard-WSL2 #1 SMP Fri Jan 27 02:56:13 UTC 2023 Platform: Unix PSCompatibleVersions: 1.0, 2.0, 3.0, 4.0, 5.0, 5.1.10032.0, 6.0.0, 6.1.0, 6.2.0, 7.0.0, 7.1.0, 7.2.0, 7.3.3 PSRemotingProtocolVersion: 2.3 SerializationVersion: 1.1.0.1 WSManStackVersion: 3.0 ********************** NOTE: IPAM Deployment Type: Function INFO: Fetching Tenant ID from Azure PowerShell SDK INFO: Fetching Azure Cloud type from Azure PowerShell SDK INFO: Validating Azure Region selected for deployment INFO: Azure Region validated successfully INFO: Creating Azure IPAM Engine Application INFO: Creating Azure IPAM Engine Service Principal INFO: Creating Azure IPAM Engine Secret INFO: Azure IPAM Engine & UI Applications/Service Principals created successfully INFO: Logging in to Microsoft Graph INFO: Granting admin consent for Azure Service Management API permissions assigned to IPAM Engine application INFO: Admin consent for Azure Service Management API permissions granted successfully INFO: Deploying IPAM bicep templates PS>TerminatingError(New-AzDeployment): "The running command stopped because the preference variable "ErrorActionPreference" or common parameter is set to Stop: 12:19:54 - Error: Code=InvalidTemplateDeployment; Message=The template deployment failed with multiple errors. Please see details for more information. " >> TerminatingError(New-AzDeployment): "The running command stopped because the preference variable "ErrorActionPreference" or common parameter is set to Stop: 12:19:54 - Error: Code=InvalidTemplateDeployment; Message=The template deployment failed with multiple errors. Please see details for more information. " >> TerminatingError(New-AzDeployment): "The running command stopped because the preference variable "ErrorActionPreference" or common parameter is set to Stop: 12:19:54 - Error: Code=InvalidTemplateDeployment; Message=The template deployment failed with multiple errors. Please see details for more information. " ERROR: Unable to deploy Azure IPAM solution due to an exception, see logs for detailed information! Run Log: ../logs/deploy_20230405121940PM.log Error Log: ../logs/error_20230405121940PM.log ********************** PowerShell transcript end End time: 20230405121954 **********************  
```

**Error Log**
```
New-AzDeployment: /home/craig/craig-workspace/azure-ipam/deploy/deploy.ps1:703 Line |  703 |        New-AzSubscriptionDeployment `      |        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~      | 12:19:54 - Error: Code=InvalidTemplateDeployment; Message=The template deployment failed with multiple errors. Please see details for more information.  
```

**Comment by DCMattyG** [comment] 2023-04-05 15:06
Good morning @craigthackerx, and thank you so much for opening this issue!

At first glance, this doesn't appear per-se an Azure IPAM Deployment Script issue, but something within Azure is not allowing the deployment to complete. Can you try checking the Deployment results within the Azure portal?

You can find the Deployment details under the subscription like this:

![image](https://user-images.githubusercontent.com/12955732/230122632-581598f9-3449-4913-be45-9e713e5c9378.png)

I would expect you to see a failure here (mine shows success). Click on the failed deployment for additional details like so:

![image](https://user-images.githubusercontent.com/12955732/230122786-5d2f03ae-91f7-4128-b742-ed72ccba43c2.png)

Here you should be able to see which component(s) failed, and perhaps a more clear reason as to why. It could be something like resource availability, quota limit, Azure Policy, etc.

I'm also more than happy to hop on a 1:1 session with you to drill down on the exact root cause at any time. Please feel free to reach out to me at Matthew.Garrett@microsoft.com, and we can get something scheduled.

I know we'll get this resolved soon, looking forward to driving this to closure with you!

**Comment by DCMattyG** [comment] 2023-04-12 15:52
Good morning @craigthackerx, I just wanted to circle back with you on this issue to see if you've been able to look a bit deeper into where the deployment failed in the Azure portal, or if you'd like to schedule some time for us to dive into this together.

Let me know how things are going, we're always here to help!

**Comment by craigthackerx** [comment] 2023-04-13 18:04
> Good morning @craigthackerx, I just wanted to circle back with you on this issue to see if you've been able to look a bit deeper into where the deployment failed in the Azure portal, or if you'd like to schedule some time for us to dive into this together.
> 
> Let me know how things are going, we're always here to help!

Apologies for the slow reply, I haven't had a chance to reply over the holidays.

Oddly, I struggled to replicate the issue on another tenant I had.  The tenant I was testing it in had more controls in place, so I find likely that something was interfering with the script, where as the Dev/Test tenant I have has little in the way of control.

You may wish to close this issue and I'll get back to you on here if I can replicate it, I can test what I wanted to test on my personal tenant.

**Comment by DCMattyG** [comment] 2023-04-13 18:15
Sounds great @craigthackerx! I've seen similar issues before where something like Azure Policy was preventing some portion of the Azure IPAM infrastructure from deploying.

In the future, you can add the "-Debug" flag to the Deploy.ps1 and it will produce **EXTREMELY** verbose logs (in the /logs folder). Generally we can parse through those to locate the more precise problem happening during the Bicep template deployment. As always, we're more than happy to assist with this once the Debug logs are generated.

For now I'll close this out, but we're here to help at any point in time!

**Closed by DCMattyG** 2023-04-13 18:15 UTC
Labels: help wanted
