### ISSUE TITLE
Restrict access to a group within a Azure AD tenant.

### ISSUE THREAD

**Issue by jeevanions** [Azure/ipam#100] opened 2023-03-30 13:25 UTC
The IPAM web app is only used by a specific team who manages the IP address allocation. The current implementation connects with the Azure AD and any user from the tenant can access the application.

We would like to restrict access only to users from an AD group. Is this something we can configure with the current implementation? Please advice.

**Comment by DCMattyG** [comment] 2023-03-30 16:41
Hey @jeevanions, this appears to be a duplicate of your request from the bottom of #96. Would you like to close the other issue so we can discuss this here?

Pasting my response from #96 for reference...

At this moment there's no way within the Azure IPAM tool to strictly control user access.

There is the construct of Admins/Non-Admins, and for non-admins, when they login to the Azure IPAM tool, the only things they are presented are what they can already see today within the Azure Portal itself because we're using their same AuthN/AuthZ to query Azure Resource Graph.

There are two options here:
1. You can leverage pre-existing mechanisms in Azure to control access to the App Registration for the Azure IPAM UI, which you can read about [here](https://learn.microsoft.com/en-us/azure/active-directory/develop/howto-restrict-your-app-to-a-set-of-users).
2. I can built in a user-management mechanism, but that seems like it might be an extra layer not needed given that all the IPAM tool is exposing is what users can already see (outside of the IPAM specific constructs).

I'm more than open to your thoughts on this matter. Please let me know what you'd like to see as next steps. Thanks!

**Comment by jeevanions** [comment] 2023-03-30 17:18
@DCMattyG Thank you for your quick response. 

I totally get that. I am trying the first option now. Will update how it goes.

**Comment by jeevanions** [comment] 2023-03-31 10:16
@DCMattyG This worked nicely. This is what we did.

1. From Azure portal - AD - Find the Enterprise Applications for the UI App Reg
2. On the application's Overview page, under Manage, select Properties. Locate the setting Assignment required and set it to 'yes'
3. Under Manage, select the Users and groups, then select Add user/group. Then add the users/groups who would be the audience for this web application. 
Thats it. Only users/groups added here would be allowed to access this web application.

**Comment by DCMattyG** [comment] 2023-04-12 18:46
Hi @jeevanions, I was just circling back on this issue, and I believe it is now resolved. Would it be ok if we close this for now, and we will work on adding your solution (above) to our documentation so others can reference it in the future?

**Comment by jeevhub** [comment] 2023-04-13 11:49
Yes it is

**Comment by DCMattyG** [comment] 2023-04-13 16:17
Thanks so much, we'll get this added into the documentation right away!

**Closed by DCMattyG** 2023-04-13 16:17 UTC
Labels: documentation
